name: Upload Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build
        run: bundle exec jekyll build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ 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 }}
          publish_dir: ./_site
