name: Deploy to GitHub Pages1

on:
  push:
    branches:
      - main  # Modify to match your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Your Website  # Modify this step as needed
        run: |
          # Add commands to build your website (e.g., npm run build, jekyll build, etc.)

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ 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 }}
          publish_dir: ./path/to/your/website  # Modify this to point to your built website
